GO_MODULE ?= __GO_MODULE__
GO ?= go
GOFMT ?= gofmt
DOCKER ?= docker
STATICCHECK_VERSION ?= v0.7.0
STATICCHECK ?= $(GO) run honnef.co/go/tools/cmd/staticcheck@$(STATICCHECK_VERSION)
STATICCHECK_GOFLAGS ?= -buildvcs=false
COVERAGE_PROFILE ?= coverage.out
COVERAGE_REPORT ?= coverage.txt
COVERAGE_THRESHOLD ?= 85.0
PROJECT_NAME ?= __PROJECT_NAME__
PROJECT_DESC ?= __PROJECT_DESC__
FEATURE_NAME ?= __FEATURE_NAME__
METRIC_NAMESPACE ?= __METRIC_NAMESPACE__
DEFAULT_PORT ?= :__DEFAULT_PORT__
MAIN_PACKAGE ?= ./cmd
DIST_DIR ?= dist
BUILD_OUTPUT ?= $(DIST_DIR)/$(PROJECT_NAME)
CGO_ENABLED ?= 0
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
BRANCH ?= $(shell git rev-parse --abbrev-ref HEAD 2>/dev/null || echo dev)
REVISION ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo dev)
BUILD_USER ?= $(shell whoami 2>/dev/null || echo unknown)
BUILD_DATE ?= $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
LDFLAGS ?= -s -w \
 -X 'github.com/prometheus/common/version.Version=$(VERSION)' \
 -X 'github.com/prometheus/common/version.Branch=$(BRANCH)' \
 -X 'github.com/prometheus/common/version.Revision=$(REVISION)' \
 -X 'github.com/prometheus/common/version.BuildUser=$(BUILD_USER)' \
 -X 'github.com/prometheus/common/version.BuildDate=$(BUILD_DATE)' \
 -X '$(GO_MODULE)/internal/exporter.defaultExporterName=$(PROJECT_NAME)' \
 -X '$(GO_MODULE)/internal/exporter.defaultExporterDescription=$(PROJECT_DESC)' \
 -X '$(GO_MODULE)/internal/exporter.defaultFeatureName=$(FEATURE_NAME)' \
 -X '$(GO_MODULE)/internal/exporter.defaultMetricNamespace=$(METRIC_NAMESPACE)' \
 -X '$(GO_MODULE)/internal/exporter.defaultListenAddress=$(DEFAULT_PORT)'
PLATFORMS ?= linux/amd64 linux/arm64 darwin/amd64 darwin/arm64
IMAGE_TAG ?= $(VERSION)
DOCKER_IMAGE ?= $(PROJECT_NAME):$(IMAGE_TAG)
DOCKER_ENTRYPOINT_NAME ?= exporter
DOCKER_HTTP_IMAGE ?= busybox:1.36
DOCKER_SMOKE_METRIC ?= __DOCKER_SMOKE_METRIC__
DOCKER_PLATFORMS ?= linux/amd64,linux/arm64
PROMTOOL_IMAGE ?= prom/prometheus:latest
DOCKER_COMPOSE ?= $(DOCKER) compose
SMOKE_DOCKER_IMAGE ?= $(PROJECT_NAME):smoke
SMOKE_VERSION ?= v9.8.7
SMOKE_BRANCH ?= smoke-branch
SMOKE_REVISION ?= abc123def
SMOKE_BUILD_USER ?= smoke-test
SMOKE_BUILD_DATE ?= 2026-05-17T00:00:00Z
SMOKE_BINARY ?= $(DIST_DIR)/$(PROJECT_NAME)
SMOKE_LDFLAGS ?= -s -w \
 -X 'github.com/prometheus/common/version.Version=$(SMOKE_VERSION)' \
 -X 'github.com/prometheus/common/version.Branch=$(SMOKE_BRANCH)' \
 -X 'github.com/prometheus/common/version.Revision=$(SMOKE_REVISION)' \
 -X 'github.com/prometheus/common/version.BuildUser=$(SMOKE_BUILD_USER)' \
 -X 'github.com/prometheus/common/version.BuildDate=$(SMOKE_BUILD_DATE)' \
 -X '$(GO_MODULE)/internal/exporter.defaultExporterName=$(PROJECT_NAME)' \
 -X '$(GO_MODULE)/internal/exporter.defaultExporterDescription=$(PROJECT_DESC)' \
 -X '$(GO_MODULE)/internal/exporter.defaultFeatureName=$(FEATURE_NAME)' \
 -X '$(GO_MODULE)/internal/exporter.defaultMetricNamespace=$(METRIC_NAMESPACE)' \
 -X '$(GO_MODULE)/internal/exporter.defaultListenAddress=$(DEFAULT_PORT)'
